INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (1, 'MARIO DE ANDRADE','SÂO PAULO','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (2, 'GUIMARAES ROSA','SANTOS','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (3, 'MANUEL BANDEIRA','SOROCABA','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (4, 'JOSE DE ALENCAR','CAMPINAS','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (5, 'CECILIA MEIRELES','SUMARE','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (6, 'CLARICE LISPECTOR','HORTOLÂNDIA','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (7, 'CARLOS DRUMMOND DE ANDRADE','PIRACICABA','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (8, 'GRACILIANO RAMOS','OSASCO','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (9, 'MACHADO DE ASSIS','ITAPEVI','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (10,'ÁLVARES DE AZEVEDO','SÂO PAULO','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (11,'ALUÍSIO AZEVEDO','SÂO PAULO','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (12,'OLAVO BILAC','SANTOS','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (13,'MONTEIRO LOBATO','SOROCABA','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (14,'CORA CORALINA','CAMPINAS','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (15,'MARIO QUINTANA','SUMARE','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (16,'JORGE AMADO','HORTOLÂNDIA','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (17,'NELSON RODRIGUES','PIRACICABA','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (18,'ARIANO SUASSUNA','OSASCO','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (19,'CONCEIÇÃO EVARISTO','ITAPEVI','SP');
INSERT INTO dbtestwk.clientes(id,nome,cidade,uf) VALUES (20,'RUBEM FONSECA','SANTOS','SP');

INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (1,  'MOUSE OPTICO', 11.90);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (2,  'TECLADO SIMPLES', 19.50);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (3,  'MONITOR 15 POL', 377.50);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (4,  'HD 500GB WD', 118.00);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (5,  'MICRO SD 32GB', 16.00);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (6,  'MICRO SD 16GB', 31.50);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (7,  'MICRO SD 8GB', 8.50);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (8,  'MICRO SD 64GB', 60.00);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (9,  'MICRO SD 128GB', 110.00);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (10, 'PLACA VIDEO NVIDEA', 225.60);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (11, 'REPETIDOR WIFI', 32.70);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (12, 'SSD 1TB KINGSTON', 331.80);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (13, 'MEMORIA PC 8GB', 53.75);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (14, 'FONTE PC 200W', 53.00);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (15, 'CASE SSD SATA', 73.00);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (16, 'CABO DE FORCA', 19.00);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (17, 'PLACA MAE KNUP', 160.50);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (18, 'CASE SLIM HD', 23.50);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (19, 'ADAPTADOR USB SOM', 183.50);
INSERT INTO dbtestwk.produtos(id, descricao, preco_venda) VALUES (20, 'PLACA PCI 3.0', 40.50);